package alguemdarua.cobbleexport

import com.cobblemon.mod.common.pokemon.Pokemon
import com.cobblemon.mod.common.api.pokemon.stats.Stats
import net.minecraft.registry.Registries

object PokemonMapper {

    // Stat display order matching Showdown convention
    private val STAT_ORDER = listOf(
        Stats.HP to "HP",
        Stats.ATTACK to "Atk",
        Stats.DEFENCE to "Def",
        Stats.SPECIAL_ATTACK to "SpA",
        Stats.SPECIAL_DEFENCE to "SpD",
        Stats.SPEED to "Spe"
    )

    /**
     * Converts a Pokemon to Pokemon Showdown text format.
     *
     * Example output:
     *   Mudkip (M) @ Leftovers
     *   Ability: Torrent
     *   Tera Type: Water
     *   Level: 50
     *   EVs: 252 HP / 4 Def / 252 SpD
     *   Calm Nature
     *   IVs: 0 Atk
     *   - Scald
     *   - Toxic
     *   - Recover
     *   - Protect
     */
    fun toShowdown(pokemon: Pokemon): String {
        val lines = mutableListOf<String>()

        // --- LINE 1: Name (Species) (Gender) @ Item ---
        lines.add(buildFirstLine(pokemon))

        // --- Ability ---
        lines.add("Ability: ${formatAbilityName(pokemon.ability.name)}")

        // --- Tera Type ---
        lines.add("Tera Type: ${formatName(pokemon.teraType.name.lowercase())}")

        // --- Level (omit if 100, Showdown default) ---
        if (pokemon.level != 100) {
            lines.add("Level: ${pokemon.level}")
        }

        // --- Shiny ---
        if (pokemon.shiny) {
            lines.add("Shiny: Yes")
        }

        // --- EVs (always show all EVs, even if 0, for clarity) ---
        val evParts = STAT_ORDER.map { (stat, label) ->
            val value = pokemon.evs[stat] ?: 0
            "${value} ${label}"
        }
        lines.add("EVs: ${evParts.joinToString(" / ")}")

        // --- Nature (uses effectiveNature = minted nature if minted, otherwise original) ---
        val natureName = pokemon.effectiveNature.name.toString()
            .lowercase()
            .substringAfter(":")
            .replaceFirstChar { it.uppercase() }
        lines.add("${natureName} Nature")

        // --- IVs (uses getEffectiveBattleIV = accounts for candies + hyper training) ---
        // Always show all IVs for clarity
        val ivParts = STAT_ORDER.map { (stat, label) ->
            val value = pokemon.ivs.getEffectiveBattleIV(stat)
            "${value} ${label}"
        }
        lines.add("IVs: ${ivParts.joinToString(" / ")}")

        // --- Moves ---
        for (move in pokemon.moveSet.getMoves()) {
            lines.add("- ${formatMoveName(move.name)}")
        }

        return lines.joinToString("\n")
    }

    /**
     * First line: Nickname (Species) (Gender) @ Item
     * - If nickname == species name, just show species
     * - Gender: (M), (F), or omitted for genderless
     * - Item: @ ItemName, or omitted if none
     */
    private fun buildFirstLine(pokemon: Pokemon): String {
        val speciesName = formatName(pokemon.species.name.lowercase())
        val nickname = pokemon.nickname?.string

        val sb = StringBuilder()

        if (nickname != null && nickname != speciesName) {
            sb.append("${nickname} (${speciesName})")
        } else {
            sb.append(speciesName)
        }

        // Gender
        when (pokemon.gender.toString()) {
            "MALE" -> sb.append(" (M)")
            "FEMALE" -> sb.append(" (F)")
        }

        // Held item
        val item = getHeldItemName(pokemon)
        if (item != null) {
            sb.append(" @ ${formatName(item)}")
        }

        return sb.toString()
    }

    private fun getHeldItemName(pokemon: Pokemon): String? {
        val stack = pokemon.heldItem()
        if (stack.isEmpty) return null
        return try {
            Registries.ITEM.getId(stack.item).path
        } catch (_: Exception) {
            stack.item.name.string.lowercase().replace(" ", "_")
        }
    }

    /**
     * Converts internal names like "special_attack" or "leftovers" to "Special Attack" or "Leftovers".
     * Used for species names, item names, tera types — anything that uses underscores/hyphens as separators.
     */
    private fun formatName(name: String): String {
        return name.split("_", "-").joinToString(" ") { word ->
            word.replaceFirstChar { it.uppercase() }
        }
    }

    /**
     * Converts internal ability names to proper display names.
     * Cobblemon stores abilities as concatenated lowercase (e.g. "neutralizinggas").
     * Uses a comprehensive lookup map sourced from Pokemon Showdown's official data.
     */
    private fun formatAbilityName(internalName: String): String {
        val key = internalName.lowercase().replace("_", "").replace("-", "").replace(" ", "")
        return ABILITY_NAMES[key] ?: formatName(internalName)
    }

    /**
     * Converts internal move names to proper display names.
     * Cobblemon stores moves as concatenated lowercase (e.g. "thunderpunch").
     * Uses a comprehensive lookup map sourced from Pokemon Showdown's official data.
     */
    private fun formatMoveName(internalName: String): String {
        val key = internalName.lowercase().replace("_", "").replace("-", "").replace(" ", "")
        return MOVE_NAMES[key] ?: formatName(internalName)
    }

    // =============================================================================================
    //  Complete move name lookup map sourced from Pokemon Showdown official data.
    //  Maps concatenated-lowercase IDs to their proper display names.
    // =============================================================================================
    private val MOVE_NAMES = mapOf(
        "10000000voltthunderbolt" to "10,000,000 Volt Thunderbolt",
        "absorb" to "Absorb",
        "accelerock" to "Accelerock",
        "acid" to "Acid",
        "acidarmor" to "Acid Armor",
        "aciddownpour" to "Acid Downpour",
        "acidspray" to "Acid Spray",
        "acrobatics" to "Acrobatics",
        "acupressure" to "Acupressure",
        "aerialace" to "Aerial Ace",
        "aeroblast" to "Aeroblast",
        "afteryou" to "After You",
        "agility" to "Agility",
        "aircutter" to "Air Cutter",
        "airslash" to "Air Slash",
        "alloutpummeling" to "All-Out Pummeling",
        "alluringvoice" to "Alluring Voice",
        "allyswitch" to "Ally Switch",
        "amnesia" to "Amnesia",
        "anchorshot" to "Anchor Shot",
        "ancientpower" to "Ancient Power",
        "appleacid" to "Apple Acid",
        "aquacutter" to "Aqua Cutter",
        "aquajet" to "Aqua Jet",
        "aquaring" to "Aqua Ring",
        "aquastep" to "Aqua Step",
        "aquatail" to "Aqua Tail",
        "armorcannon" to "Armor Cannon",
        "armthrust" to "Arm Thrust",
        "aromatherapy" to "Aromatherapy",
        "aromaticmist" to "Aromatic Mist",
        "assist" to "Assist",
        "assurance" to "Assurance",
        "astonish" to "Astonish",
        "astralbarrage" to "Astral Barrage",
        "attackorder" to "Attack Order",
        "attract" to "Attract",
        "aurasphere" to "Aura Sphere",
        "aurawheel" to "Aura Wheel",
        "aurorabeam" to "Aurora Beam",
        "auroraveil" to "Aurora Veil",
        "autotomize" to "Autotomize",
        "avalanche" to "Avalanche",
        "axekick" to "Axe Kick",
        "babydolleyes" to "Baby-Doll Eyes",
        "baddybad" to "Baddy Bad",
        "banefulbunker" to "Baneful Bunker",
        "barbbarrage" to "Barb Barrage",
        "barrage" to "Barrage",
        "barrier" to "Barrier",
        "batonpass" to "Baton Pass",
        "beakblast" to "Beak Blast",
        "beatup" to "Beat Up",
        "behemothbash" to "Behemoth Bash",
        "behemothblade" to "Behemoth Blade",
        "belch" to "Belch",
        "bellydrum" to "Belly Drum",
        "bestow" to "Bestow",
        "bide" to "Bide",
        "bind" to "Bind",
        "bite" to "Bite",
        "bitterblade" to "Bitter Blade",
        "bittermalice" to "Bitter Malice",
        "blackholeeclipse" to "Black Hole Eclipse",
        "blastburn" to "Blast Burn",
        "blazekick" to "Blaze Kick",
        "blazingtorque" to "Blazing Torque",
        "bleakwindstorm" to "Bleakwind Storm",
        "blizzard" to "Blizzard",
        "block" to "Block",
        "bloodmoon" to "Blood Moon",
        "bloomdoom" to "Bloom Doom",
        "blueflare" to "Blue Flare",
        "bodypress" to "Body Press",
        "bodyslam" to "Body Slam",
        "boltbeak" to "Bolt Beak",
        "boltstrike" to "Bolt Strike",
        "boneclub" to "Bone Club",
        "bonemerang" to "Bonemerang",
        "bonerush" to "Bone Rush",
        "boomburst" to "Boomburst",
        "bounce" to "Bounce",
        "bouncybubble" to "Bouncy Bubble",
        "branchpoke" to "Branch Poke",
        "bravebird" to "Brave Bird",
        "breakingswipe" to "Breaking Swipe",
        "breakneckblitz" to "Breakneck Blitz",
        "brickbreak" to "Brick Break",
        "brine" to "Brine",
        "brutalswing" to "Brutal Swing",
        "bubble" to "Bubble",
        "bubblebeam" to "Bubble Beam",
        "bugbite" to "Bug Bite",
        "bugbuzz" to "Bug Buzz",
        "bulkup" to "Bulk Up",
        "bulldoze" to "Bulldoze",
        "bulletpunch" to "Bullet Punch",
        "bulletseed" to "Bullet Seed",
        "burningbulwark" to "Burning Bulwark",
        "burningjealousy" to "Burning Jealousy",
        "burnup" to "Burn Up",
        "buzzybuzz" to "Buzzy Buzz",
        "calmmind" to "Calm Mind",
        "camouflage" to "Camouflage",
        "captivate" to "Captivate",
        "catastropika" to "Catastropika",
        "ceaselessedge" to "Ceaseless Edge",
        "celebrate" to "Celebrate",
        "charge" to "Charge",
        "chargebeam" to "Charge Beam",
        "charm" to "Charm",
        "chatter" to "Chatter",
        "chillingwater" to "Chilling Water",
        "chillyreception" to "Chilly Reception",
        "chipaway" to "Chip Away",
        "chloroblast" to "Chloroblast",
        "circlethrow" to "Circle Throw",
        "clamp" to "Clamp",
        "clangingscales" to "Clanging Scales",
        "clangoroussoul" to "Clangorous Soul",
        "clangoroussoulblaze" to "Clangorous Soulblaze",
        "clearsmog" to "Clear Smog",
        "closecombat" to "Close Combat",
        "coaching" to "Coaching",
        "coil" to "Coil",
        "collisioncourse" to "Collision Course",
        "combattorque" to "Combat Torque",
        "cometpunch" to "Comet Punch",
        "comeuppance" to "Comeuppance",
        "confide" to "Confide",
        "confuseray" to "Confuse Ray",
        "confusion" to "Confusion",
        "constrict" to "Constrict",
        "continentalcrush" to "Continental Crush",
        "conversion" to "Conversion",
        "conversion2" to "Conversion 2",
        "copycat" to "Copycat",
        "coreenforcer" to "Core Enforcer",
        "corkscrewcrash" to "Corkscrew Crash",
        "corrosivegas" to "Corrosive Gas",
        "cosmicpower" to "Cosmic Power",
        "cottonguard" to "Cotton Guard",
        "cottonspore" to "Cotton Spore",
        "counter" to "Counter",
        "courtchange" to "Court Change",
        "covet" to "Covet",
        "crabhammer" to "Crabhammer",
        "craftyshield" to "Crafty Shield",
        "crosschop" to "Cross Chop",
        "crosspoison" to "Cross Poison",
        "crunch" to "Crunch",
        "crushclaw" to "Crush Claw",
        "crushgrip" to "Crush Grip",
        "curse" to "Curse",
        "cut" to "Cut",
        "darkestlariat" to "Darkest Lariat",
        "darkpulse" to "Dark Pulse",
        "darkvoid" to "Dark Void",
        "dazzlinggleam" to "Dazzling Gleam",
        "decorate" to "Decorate",
        "defendorder" to "Defend Order",
        "defensecurl" to "Defense Curl",
        "defog" to "Defog",
        "destinybond" to "Destiny Bond",
        "detect" to "Detect",
        "devastatingdrake" to "Devastating Drake",
        "diamondstorm" to "Diamond Storm",
        "dig" to "Dig",
        "direclaw" to "Dire Claw",
        "disable" to "Disable",
        "disarmingvoice" to "Disarming Voice",
        "discharge" to "Discharge",
        "dive" to "Dive",
        "dizzypunch" to "Dizzy Punch",
        "doodle" to "Doodle",
        "doomdesire" to "Doom Desire",
        "doubleedge" to "Double-Edge",
        "doublehit" to "Double Hit",
        "doubleironbash" to "Double Iron Bash",
        "doublekick" to "Double Kick",
        "doubleshock" to "Double Shock",
        "doubleslap" to "Double Slap",
        "doubleteam" to "Double Team",
        "dracometeor" to "Draco Meteor",
        "dragonascent" to "Dragon Ascent",
        "dragonbreath" to "Dragon Breath",
        "dragoncheer" to "Dragon Cheer",
        "dragonclaw" to "Dragon Claw",
        "dragondance" to "Dragon Dance",
        "dragondarts" to "Dragon Darts",
        "dragonenergy" to "Dragon Energy",
        "dragonhammer" to "Dragon Hammer",
        "dragonpulse" to "Dragon Pulse",
        "dragonrage" to "Dragon Rage",
        "dragonrush" to "Dragon Rush",
        "dragontail" to "Dragon Tail",
        "drainingkiss" to "Draining Kiss",
        "drainpunch" to "Drain Punch",
        "dreameater" to "Dream Eater",
        "drillpeck" to "Drill Peck",
        "drillrun" to "Drill Run",
        "drumbeating" to "Drum Beating",
        "dualchop" to "Dual Chop",
        "dualwingbeat" to "Dual Wingbeat",
        "dynamaxcannon" to "Dynamax Cannon",
        "dynamicpunch" to "Dynamic Punch",
        "earthpower" to "Earth Power",
        "earthquake" to "Earthquake",
        "echoedvoice" to "Echoed Voice",
        "eerieimpulse" to "Eerie Impulse",
        "eeriespell" to "Eerie Spell",
        "eggbomb" to "Egg Bomb",
        "electricterrain" to "Electric Terrain",
        "electrify" to "Electrify",
        "electroball" to "Electro Ball",
        "electrodrift" to "Electro Drift",
        "electroshot" to "Electro Shot",
        "electroweb" to "Electroweb",
        "embargo" to "Embargo",
        "ember" to "Ember",
        "encore" to "Encore",
        "endeavor" to "Endeavor",
        "endure" to "Endure",
        "energyball" to "Energy Ball",
        "entrainment" to "Entrainment",
        "eruption" to "Eruption",
        "esperwing" to "Esper Wing",
        "eternabeam" to "Eternabeam",
        "expandingforce" to "Expanding Force",
        "explosion" to "Explosion",
        "extrasensory" to "Extrasensory",
        "extremeevoboost" to "Extreme Evoboost",
        "extremespeed" to "Extreme Speed",
        "facade" to "Facade",
        "fairylock" to "Fairy Lock",
        "fairywind" to "Fairy Wind",
        "fakeout" to "Fake Out",
        "faketears" to "Fake Tears",
        "falsesurrender" to "False Surrender",
        "falseswipe" to "False Swipe",
        "featherdance" to "Feather Dance",
        "feint" to "Feint",
        "feintattack" to "Feint Attack",
        "fellstinger" to "Fell Stinger",
        "ficklebeam" to "Fickle Beam",
        "fierydance" to "Fiery Dance",
        "fierywrath" to "Fiery Wrath",
        "filletaway" to "Fillet Away",
        "finalgambit" to "Final Gambit",
        "fireblast" to "Fire Blast",
        "firefang" to "Fire Fang",
        "firelash" to "Fire Lash",
        "firepledge" to "Fire Pledge",
        "firepunch" to "Fire Punch",
        "firespin" to "Fire Spin",
        "firstimpression" to "First Impression",
        "fishiousrend" to "Fishious Rend",
        "fissure" to "Fissure",
        "flail" to "Flail",
        "flameburst" to "Flame Burst",
        "flamecharge" to "Flame Charge",
        "flamethrower" to "Flamethrower",
        "flamewheel" to "Flame Wheel",
        "flareblitz" to "Flare Blitz",
        "flash" to "Flash",
        "flashcannon" to "Flash Cannon",
        "flatter" to "Flatter",
        "fleurcannon" to "Fleur Cannon",
        "fling" to "Fling",
        "flipturn" to "Flip Turn",
        "floatyfall" to "Floaty Fall",
        "floralhealing" to "Floral Healing",
        "flowershield" to "Flower Shield",
        "flowertrick" to "Flower Trick",
        "fly" to "Fly",
        "flyingpress" to "Flying Press",
        "focusblast" to "Focus Blast",
        "focusenergy" to "Focus Energy",
        "focuspunch" to "Focus Punch",
        "followme" to "Follow Me",
        "forcepalm" to "Force Palm",
        "foresight" to "Foresight",
        "forestscurse" to "Forest's Curse",
        "foulplay" to "Foul Play",
        "freezedry" to "Freeze-Dry",
        "freezeshock" to "Freeze Shock",
        "freezingglare" to "Freezing Glare",
        "freezyfrost" to "Freezy Frost",
        "frenzyplant" to "Frenzy Plant",
        "frostbreath" to "Frost Breath",
        "frustration" to "Frustration",
        "furyattack" to "Fury Attack",
        "furycutter" to "Fury Cutter",
        "furyswipes" to "Fury Swipes",
        "fusionbolt" to "Fusion Bolt",
        "fusionflare" to "Fusion Flare",
        "futuresight" to "Future Sight",
        "gastroacid" to "Gastro Acid",
        "geargrind" to "Gear Grind",
        "gearup" to "Gear Up",
        "genesissupernova" to "Genesis Supernova",
        "geomancy" to "Geomancy",
        "gigadrain" to "Giga Drain",
        "gigaimpact" to "Giga Impact",
        "gigatonhammer" to "Gigaton Hammer",
        "gigavolthavoc" to "Gigavolt Havoc",
        "glaciallance" to "Glacial Lance",
        "glaciate" to "Glaciate",
        "glaiverush" to "Glaive Rush",
        "glare" to "Glare",
        "glitzyglow" to "Glitzy Glow",
        "gmaxbefuddle" to "G-Max Befuddle",
        "gmaxcannonade" to "G-Max Cannonade",
        "gmaxcentiferno" to "G-Max Centiferno",
        "gmaxchistrike" to "G-Max Chi Strike",
        "gmaxcuddle" to "G-Max Cuddle",
        "gmaxdepletion" to "G-Max Depletion",
        "gmaxdrumsolo" to "G-Max Drum Solo",
        "gmaxfinale" to "G-Max Finale",
        "gmaxfireball" to "G-Max Fireball",
        "gmaxfoamburst" to "G-Max Foam Burst",
        "gmaxgoldrush" to "G-Max Gold Rush",
        "gmaxgravitas" to "G-Max Gravitas",
        "gmaxhydrosnipe" to "G-Max Hydrosnipe",
        "gmaxmalodor" to "G-Max Malodor",
        "gmaxmeltdown" to "G-Max Meltdown",
        "gmaxoneblow" to "G-Max One Blow",
        "gmaxrapidflow" to "G-Max Rapid Flow",
        "gmaxreplenish" to "G-Max Replenish",
        "gmaxresonance" to "G-Max Resonance",
        "gmaxsandblast" to "G-Max Sandblast",
        "gmaxsmite" to "G-Max Smite",
        "gmaxsnooze" to "G-Max Snooze",
        "gmaxsteelsurge" to "G-Max Steelsurge",
        "gmaxstonesurge" to "G-Max Stonesurge",
        "gmaxstunshock" to "G-Max Stun Shock",
        "gmaxsweetness" to "G-Max Sweetness",
        "gmaxtartness" to "G-Max Tartness",
        "gmaxterror" to "G-Max Terror",
        "gmaxvinelash" to "G-Max Vine Lash",
        "gmaxvolcalith" to "G-Max Volcalith",
        "gmaxvoltcrash" to "G-Max Volt Crash",
        "gmaxwildfire" to "G-Max Wildfire",
        "gmaxwindrage" to "G-Max Wind Rage",
        "grassknot" to "Grass Knot",
        "grasspledge" to "Grass Pledge",
        "grasswhistle" to "Grass Whistle",
        "grassyglide" to "Grassy Glide",
        "grassyterrain" to "Grassy Terrain",
        "gravapple" to "Grav Apple",
        "gravity" to "Gravity",
        "growl" to "Growl",
        "growth" to "Growth",
        "grudge" to "Grudge",
        "guardianofalola" to "Guardian of Alola",
        "guardsplit" to "Guard Split",
        "guardswap" to "Guard Swap",
        "guillotine" to "Guillotine",
        "gunkshot" to "Gunk Shot",
        "gust" to "Gust",
        "gyroball" to "Gyro Ball",
        "hail" to "Hail",
        "hammerarm" to "Hammer Arm",
        "happyhour" to "Happy Hour",
        "harden" to "Harden",
        "hardpress" to "Hard Press",
        "haze" to "Haze",
        "headbutt" to "Headbutt",
        "headcharge" to "Head Charge",
        "headlongrush" to "Headlong Rush",
        "headsmash" to "Head Smash",
        "healbell" to "Heal Bell",
        "healblock" to "Heal Block",
        "healingwish" to "Healing Wish",
        "healorder" to "Heal Order",
        "healpulse" to "Heal Pulse",
        "heartstamp" to "Heart Stamp",
        "heartswap" to "Heart Swap",
        "heatcrash" to "Heat Crash",
        "heatwave" to "Heat Wave",
        "heavyslam" to "Heavy Slam",
        "helpinghand" to "Helping Hand",
        "hex" to "Hex",
        "hiddenpower" to "Hidden Power",
        "hiddenpowerbug" to "Hidden Power Bug",
        "hiddenpowerdark" to "Hidden Power Dark",
        "hiddenpowerdragon" to "Hidden Power Dragon",
        "hiddenpowerelectric" to "Hidden Power Electric",
        "hiddenpowerfighting" to "Hidden Power Fighting",
        "hiddenpowerfire" to "Hidden Power Fire",
        "hiddenpowerflying" to "Hidden Power Flying",
        "hiddenpowerghost" to "Hidden Power Ghost",
        "hiddenpowergrass" to "Hidden Power Grass",
        "hiddenpowerground" to "Hidden Power Ground",
        "hiddenpowerice" to "Hidden Power Ice",
        "hiddenpowerpoison" to "Hidden Power Poison",
        "hiddenpowerpsychic" to "Hidden Power Psychic",
        "hiddenpowerrock" to "Hidden Power Rock",
        "hiddenpowersteel" to "Hidden Power Steel",
        "hiddenpowerwater" to "Hidden Power Water",
        "highhorsepower" to "High Horsepower",
        "highjumpkick" to "High Jump Kick",
        "holdback" to "Hold Back",
        "holdhands" to "Hold Hands",
        "honeclaws" to "Hone Claws",
        "hornattack" to "Horn Attack",
        "horndrill" to "Horn Drill",
        "hornleech" to "Horn Leech",
        "howl" to "Howl",
        "hurricane" to "Hurricane",
        "hydrocannon" to "Hydro Cannon",
        "hydropump" to "Hydro Pump",
        "hydrosteam" to "Hydro Steam",
        "hydrovortex" to "Hydro Vortex",
        "hyperbeam" to "Hyper Beam",
        "hyperdrill" to "Hyper Drill",
        "hyperfang" to "Hyper Fang",
        "hyperspacefury" to "Hyperspace Fury",
        "hyperspacehole" to "Hyperspace Hole",
        "hypervoice" to "Hyper Voice",
        "hypnosis" to "Hypnosis",
        "iceball" to "Ice Ball",
        "icebeam" to "Ice Beam",
        "iceburn" to "Ice Burn",
        "icefang" to "Ice Fang",
        "icehammer" to "Ice Hammer",
        "icepunch" to "Ice Punch",
        "iceshard" to "Ice Shard",
        "icespinner" to "Ice Spinner",
        "iciclecrash" to "Icicle Crash",
        "iciclespear" to "Icicle Spear",
        "icywind" to "Icy Wind",
        "imprison" to "Imprison",
        "incinerate" to "Incinerate",
        "infernalparade" to "Infernal Parade",
        "inferno" to "Inferno",
        "infernooverdrive" to "Inferno Overdrive",
        "infestation" to "Infestation",
        "ingrain" to "Ingrain",
        "instruct" to "Instruct",
        "iondeluge" to "Ion Deluge",
        "irondefense" to "Iron Defense",
        "ironhead" to "Iron Head",
        "irontail" to "Iron Tail",
        "ivycudgel" to "Ivy Cudgel",
        "jawlock" to "Jaw Lock",
        "jetpunch" to "Jet Punch",
        "judgment" to "Judgment",
        "jumpkick" to "Jump Kick",
        "junglehealing" to "Jungle Healing",
        "karatechop" to "Karate Chop",
        "kinesis" to "Kinesis",
        "kingsshield" to "King's Shield",
        "knockoff" to "Knock Off",
        "kowtowcleave" to "Kowtow Cleave",
        "landswrath" to "Land's Wrath",
        "laserfocus" to "Laser Focus",
        "lashout" to "Lash Out",
        "lastresort" to "Last Resort",
        "lastrespects" to "Last Respects",
        "lavaplume" to "Lava Plume",
        "leafage" to "Leafage",
        "leafblade" to "Leaf Blade",
        "leafstorm" to "Leaf Storm",
        "leaftornado" to "Leaf Tornado",
        "leechlife" to "Leech Life",
        "leechseed" to "Leech Seed",
        "leer" to "Leer",
        "letssnuggleforever" to "Let's Snuggle Forever",
        "lick" to "Lick",
        "lifedew" to "Life Dew",
        "lightofruin" to "Light of Ruin",
        "lightscreen" to "Light Screen",
        "lightthatburnsthesky" to "Light That Burns the Sky",
        "liquidation" to "Liquidation",
        "lockon" to "Lock-On",
        "lovelykiss" to "Lovely Kiss",
        "lowkick" to "Low Kick",
        "lowsweep" to "Low Sweep",
        "luckychant" to "Lucky Chant",
        "luminacrash" to "Lumina Crash",
        "lunarblessing" to "Lunar Blessing",
        "lunardance" to "Lunar Dance",
        "lunge" to "Lunge",
        "lusterpurge" to "Luster Purge",
        "machpunch" to "Mach Punch",
        "magicalleaf" to "Magical Leaf",
        "magicaltorque" to "Magical Torque",
        "magiccoat" to "Magic Coat",
        "magicpowder" to "Magic Powder",
        "magicroom" to "Magic Room",
        "magmastorm" to "Magma Storm",
        "magnetbomb" to "Magnet Bomb",
        "magneticflux" to "Magnetic Flux",
        "magnetrise" to "Magnet Rise",
        "magnitude" to "Magnitude",
        "makeitrain" to "Make It Rain",
        "maliciousmoonsault" to "Malicious Moonsault",
        "malignantchain" to "Malignant Chain",
        "matblock" to "Mat Block",
        "matchagotcha" to "Matcha Gotcha",
        "maxairstream" to "Max Airstream",
        "maxdarkness" to "Max Darkness",
        "maxflare" to "Max Flare",
        "maxflutterby" to "Max Flutterby",
        "maxgeyser" to "Max Geyser",
        "maxguard" to "Max Guard",
        "maxhailstorm" to "Max Hailstorm",
        "maxknuckle" to "Max Knuckle",
        "maxlightning" to "Max Lightning",
        "maxmindstorm" to "Max Mindstorm",
        "maxooze" to "Max Ooze",
        "maxovergrowth" to "Max Overgrowth",
        "maxphantasm" to "Max Phantasm",
        "maxquake" to "Max Quake",
        "maxrockfall" to "Max Rockfall",
        "maxstarfall" to "Max Starfall",
        "maxsteelspike" to "Max Steelspike",
        "maxstrike" to "Max Strike",
        "maxwyrmwind" to "Max Wyrmwind",
        "meanlook" to "Mean Look",
        "meditate" to "Meditate",
        "mefirst" to "Me First",
        "megadrain" to "Mega Drain",
        "megahorn" to "Megahorn",
        "megakick" to "Mega Kick",
        "megapunch" to "Mega Punch",
        "memento" to "Memento",
        "menacingmoonrazemaelstrom" to "Menacing Moonraze Maelstrom",
        "metalburst" to "Metal Burst",
        "metalclaw" to "Metal Claw",
        "metalsound" to "Metal Sound",
        "meteorassault" to "Meteor Assault",
        "meteorbeam" to "Meteor Beam",
        "meteormash" to "Meteor Mash",
        "metronome" to "Metronome",
        "mightycleave" to "Mighty Cleave",
        "milkdrink" to "Milk Drink",
        "mimic" to "Mimic",
        "mindblown" to "Mind Blown",
        "mindreader" to "Mind Reader",
        "minimize" to "Minimize",
        "miracleeye" to "Miracle Eye",
        "mirrorcoat" to "Mirror Coat",
        "mirrormove" to "Mirror Move",
        "mirrorshot" to "Mirror Shot",
        "mist" to "Mist",
        "mistball" to "Mist Ball",
        "mistyexplosion" to "Misty Explosion",
        "mistyterrain" to "Misty Terrain",
        "moonblast" to "Moonblast",
        "moongeistbeam" to "Moongeist Beam",
        "moonlight" to "Moonlight",
        "morningsun" to "Morning Sun",
        "mortalspin" to "Mortal Spin",
        "mountaingale" to "Mountain Gale",
        "mudbomb" to "Mud Bomb",
        "muddywater" to "Muddy Water",
        "mudshot" to "Mud Shot",
        "mudslap" to "Mud-Slap",
        "mudsport" to "Mud Sport",
        "multiattack" to "Multi-Attack",
        "mysticalfire" to "Mystical Fire",
        "mysticalpower" to "Mystical Power",
        "nastyplot" to "Nasty Plot",
        "naturalgift" to "Natural Gift",
        "naturepower" to "Nature Power",
        "naturesmadness" to "Nature's Madness",
        "needlearm" to "Needle Arm",
        "neverendingnightmare" to "Never-Ending Nightmare",
        "nightdaze" to "Night Daze",
        "nightmare" to "Nightmare",
        "nightshade" to "Night Shade",
        "nightslash" to "Night Slash",
        "nihillight" to "Nihil Light",
        "nobleroar" to "Noble Roar",
        "noretreat" to "No Retreat",
        "noxioustorque" to "Noxious Torque",
        "nuzzle" to "Nuzzle",
        "oblivionwing" to "Oblivion Wing",
        "obstruct" to "Obstruct",
        "oceanicoperetta" to "Oceanic Operetta",
        "octazooka" to "Octazooka",
        "octolock" to "Octolock",
        "odorsleuth" to "Odor Sleuth",
        "ominouswind" to "Ominous Wind",
        "orderup" to "Order Up",
        "originpulse" to "Origin Pulse",
        "outrage" to "Outrage",
        "overdrive" to "Overdrive",
        "overheat" to "Overheat",
        "painsplit" to "Pain Split",
        "paleowave" to "Paleo Wave",
        "paraboliccharge" to "Parabolic Charge",
        "partingshot" to "Parting Shot",
        "payback" to "Payback",
        "payday" to "Pay Day",
        "peck" to "Peck",
        "perishsong" to "Perish Song",
        "petalblizzard" to "Petal Blizzard",
        "petaldance" to "Petal Dance",
        "phantomforce" to "Phantom Force",
        "photongeyser" to "Photon Geyser",
        "pikapapow" to "Pika Papow",
        "pinmissile" to "Pin Missile",
        "plasmafists" to "Plasma Fists",
        "playnice" to "Play Nice",
        "playrough" to "Play Rough",
        "pluck" to "Pluck",
        "poisonfang" to "Poison Fang",
        "poisongas" to "Poison Gas",
        "poisonjab" to "Poison Jab",
        "poisonpowder" to "Poison Powder",
        "poisonsting" to "Poison Sting",
        "poisontail" to "Poison Tail",
        "polarflare" to "Polar Flare",
        "pollenpuff" to "Pollen Puff",
        "poltergeist" to "Poltergeist",
        "populationbomb" to "Population Bomb",
        "pounce" to "Pounce",
        "pound" to "Pound",
        "powder" to "Powder",
        "powdersnow" to "Powder Snow",
        "powergem" to "Power Gem",
        "powershift" to "Power Shift",
        "powersplit" to "Power Split",
        "powerswap" to "Power Swap",
        "powertrick" to "Power Trick",
        "powertrip" to "Power Trip",
        "poweruppunch" to "Power-Up Punch",
        "powerwhip" to "Power Whip",
        "precipiceblades" to "Precipice Blades",
        "present" to "Present",
        "prismaticlaser" to "Prismatic Laser",
        "protect" to "Protect",
        "psybeam" to "Psybeam",
        "psyblade" to "Psyblade",
        "psychic" to "Psychic",
        "psychicfangs" to "Psychic Fangs",
        "psychicnoise" to "Psychic Noise",
        "psychicterrain" to "Psychic Terrain",
        "psychoboost" to "Psycho Boost",
        "psychocut" to "Psycho Cut",
        "psychoshift" to "Psycho Shift",
        "psychup" to "Psych Up",
        "psyshieldbash" to "Psyshield Bash",
        "psyshock" to "Psyshock",
        "psystrike" to "Psystrike",
        "psywave" to "Psywave",
        "pulverizingpancake" to "Pulverizing Pancake",
        "punishment" to "Punishment",
        "purify" to "Purify",
        "pursuit" to "Pursuit",
        "pyroball" to "Pyro Ball",
        "quash" to "Quash",
        "quickattack" to "Quick Attack",
        "quickguard" to "Quick Guard",
        "quiverdance" to "Quiver Dance",
        "rage" to "Rage",
        "ragefist" to "Rage Fist",
        "ragepowder" to "Rage Powder",
        "ragingbull" to "Raging Bull",
        "ragingfury" to "Raging Fury",
        "raindance" to "Rain Dance",
        "rapidspin" to "Rapid Spin",
        "razorleaf" to "Razor Leaf",
        "razorshell" to "Razor Shell",
        "razorwind" to "Razor Wind",
        "recover" to "Recover",
        "recycle" to "Recycle",
        "reflect" to "Reflect",
        "reflecttype" to "Reflect Type",
        "refresh" to "Refresh",
        "relicsong" to "Relic Song",
        "rest" to "Rest",
        "retaliate" to "Retaliate",
        "return" to "Return",
        "revelationdance" to "Revelation Dance",
        "revenge" to "Revenge",
        "reversal" to "Reversal",
        "revivalblessing" to "Revival Blessing",
        "risingvoltage" to "Rising Voltage",
        "roar" to "Roar",
        "roaroftime" to "Roar of Time",
        "rockblast" to "Rock Blast",
        "rockclimb" to "Rock Climb",
        "rockpolish" to "Rock Polish",
        "rockslide" to "Rock Slide",
        "rocksmash" to "Rock Smash",
        "rockthrow" to "Rock Throw",
        "rocktomb" to "Rock Tomb",
        "rockwrecker" to "Rock Wrecker",
        "roleplay" to "Role Play",
        "rollingkick" to "Rolling Kick",
        "rollout" to "Rollout",
        "roost" to "Roost",
        "rototiller" to "Rototiller",
        "round" to "Round",
        "ruination" to "Ruination",
        "sacredfire" to "Sacred Fire",
        "sacredsword" to "Sacred Sword",
        "safeguard" to "Safeguard",
        "saltcure" to "Salt Cure",
        "sandattack" to "Sand Attack",
        "sandsearstorm" to "Sandsear Storm",
        "sandstorm" to "Sandstorm",
        "sandtomb" to "Sand Tomb",
        "sappyseed" to "Sappy Seed",
        "savagespinout" to "Savage Spin-Out",
        "scald" to "Scald",
        "scaleshot" to "Scale Shot",
        "scaryface" to "Scary Face",
        "scorchingsands" to "Scorching Sands",
        "scratch" to "Scratch",
        "screech" to "Screech",
        "searingshot" to "Searing Shot",
        "searingsunrazesmash" to "Searing Sunraze Smash",
        "secretpower" to "Secret Power",
        "secretsword" to "Secret Sword",
        "seedbomb" to "Seed Bomb",
        "seedflare" to "Seed Flare",
        "seismictoss" to "Seismic Toss",
        "selfdestruct" to "Self-Destruct",
        "shadowball" to "Shadow Ball",
        "shadowbone" to "Shadow Bone",
        "shadowclaw" to "Shadow Claw",
        "shadowforce" to "Shadow Force",
        "shadowpunch" to "Shadow Punch",
        "shadowsneak" to "Shadow Sneak",
        "shadowstrike" to "Shadow Strike",
        "sharpen" to "Sharpen",
        "shatteredpsyche" to "Shattered Psyche",
        "shedtail" to "Shed Tail",
        "sheercold" to "Sheer Cold",
        "shellsidearm" to "Shell Side Arm",
        "shellsmash" to "Shell Smash",
        "shelltrap" to "Shell Trap",
        "shelter" to "Shelter",
        "shiftgear" to "Shift Gear",
        "shockwave" to "Shock Wave",
        "shoreup" to "Shore Up",
        "signalbeam" to "Signal Beam",
        "silktrap" to "Silk Trap",
        "silverwind" to "Silver Wind",
        "simplebeam" to "Simple Beam",
        "sing" to "Sing",
        "sinisterarrowraid" to "Sinister Arrow Raid",
        "sizzlyslide" to "Sizzly Slide",
        "sketch" to "Sketch",
        "skillswap" to "Skill Swap",
        "skittersmack" to "Skitter Smack",
        "skullbash" to "Skull Bash",
        "skyattack" to "Sky Attack",
        "skydrop" to "Sky Drop",
        "skyuppercut" to "Sky Uppercut",
        "slackoff" to "Slack Off",
        "slam" to "Slam",
        "slash" to "Slash",
        "sleeppowder" to "Sleep Powder",
        "sleeptalk" to "Sleep Talk",
        "sludge" to "Sludge",
        "sludgebomb" to "Sludge Bomb",
        "sludgewave" to "Sludge Wave",
        "smackdown" to "Smack Down",
        "smartstrike" to "Smart Strike",
        "smellingsalts" to "Smelling Salts",
        "smog" to "Smog",
        "smokescreen" to "Smokescreen",
        "snaptrap" to "Snap Trap",
        "snarl" to "Snarl",
        "snatch" to "Snatch",
        "snipeshot" to "Snipe Shot",
        "snore" to "Snore",
        "snowscape" to "Snowscape",
        "soak" to "Soak",
        "softboiled" to "Soft-Boiled",
        "solarbeam" to "Solar Beam",
        "solarblade" to "Solar Blade",
        "sonicboom" to "Sonic Boom",
        "soulstealing7starstrike" to "Soul-Stealing 7-Star Strike",
        "spacialrend" to "Spacial Rend",
        "spark" to "Spark",
        "sparklingaria" to "Sparkling Aria",
        "sparklyswirl" to "Sparkly Swirl",
        "spectralthief" to "Spectral Thief",
        "speedswap" to "Speed Swap",
        "spicyextract" to "Spicy Extract",
        "spiderweb" to "Spider Web",
        "spikecannon" to "Spike Cannon",
        "spikes" to "Spikes",
        "spikyshield" to "Spiky Shield",
        "spinout" to "Spin Out",
        "spiritbreak" to "Spirit Break",
        "spiritshackle" to "Spirit Shackle",
        "spite" to "Spite",
        "spitup" to "Spit Up",
        "splash" to "Splash",
        "splinteredstormshards" to "Splintered Stormshards",
        "splishysplash" to "Splishy Splash",
        "spore" to "Spore",
        "spotlight" to "Spotlight",
        "springtidestorm" to "Springtide Storm",
        "stealthrock" to "Stealth Rock",
        "steameruption" to "Steam Eruption",
        "steamroller" to "Steamroller",
        "steelbeam" to "Steel Beam",
        "steelroller" to "Steel Roller",
        "steelwing" to "Steel Wing",
        "stickyweb" to "Sticky Web",
        "stockpile" to "Stockpile",
        "stokedsparksurfer" to "Stoked Sparksurfer",
        "stomp" to "Stomp",
        "stompingtantrum" to "Stomping Tantrum",
        "stoneaxe" to "Stone Axe",
        "stoneedge" to "Stone Edge",
        "storedpower" to "Stored Power",
        "stormthrow" to "Storm Throw",
        "strangesteam" to "Strange Steam",
        "strength" to "Strength",
        "strengthsap" to "Strength Sap",
        "stringshot" to "String Shot",
        "struggle" to "Struggle",
        "strugglebug" to "Struggle Bug",
        "stuffcheeks" to "Stuff Cheeks",
        "stunspore" to "Stun Spore",
        "submission" to "Submission",
        "substitute" to "Substitute",
        "subzeroslammer" to "Subzero Slammer",
        "suckerpunch" to "Sucker Punch",
        "sunnyday" to "Sunny Day",
        "sunsteelstrike" to "Sunsteel Strike",
        "supercellslam" to "Supercell Slam",
        "superfang" to "Super Fang",
        "superpower" to "Superpower",
        "supersonic" to "Supersonic",
        "supersonicskystrike" to "Supersonic Skystrike",
        "surf" to "Surf",
        "surgingstrikes" to "Surging Strikes",
        "swagger" to "Swagger",
        "swallow" to "Swallow",
        "sweetkiss" to "Sweet Kiss",
        "sweetscent" to "Sweet Scent",
        "swift" to "Swift",
        "switcheroo" to "Switcheroo",
        "swordsdance" to "Swords Dance",
        "synchronoise" to "Synchronoise",
        "synthesis" to "Synthesis",
        "syrupbomb" to "Syrup Bomb",
        "tachyoncutter" to "Tachyon Cutter",
        "tackle" to "Tackle",
        "tailglow" to "Tail Glow",
        "tailslap" to "Tail Slap",
        "tailwhip" to "Tail Whip",
        "tailwind" to "Tailwind",
        "takedown" to "Take Down",
        "takeheart" to "Take Heart",
        "tarshot" to "Tar Shot",
        "taunt" to "Taunt",
        "tearfullook" to "Tearful Look",
        "teatime" to "Teatime",
        "technoblast" to "Techno Blast",
        "tectonicrage" to "Tectonic Rage",
        "teeterdance" to "Teeter Dance",
        "telekinesis" to "Telekinesis",
        "teleport" to "Teleport",
        "temperflare" to "Temper Flare",
        "terablast" to "Tera Blast",
        "terastarstorm" to "Tera Starstorm",
        "terrainpulse" to "Terrain Pulse",
        "thief" to "Thief",
        "thousandarrows" to "Thousand Arrows",
        "thousandwaves" to "Thousand Waves",
        "thrash" to "Thrash",
        "throatchop" to "Throat Chop",
        "thunder" to "Thunder",
        "thunderbolt" to "Thunderbolt",
        "thundercage" to "Thunder Cage",
        "thunderclap" to "Thunderclap",
        "thunderfang" to "Thunder Fang",
        "thunderouskick" to "Thunderous Kick",
        "thunderpunch" to "Thunder Punch",
        "thundershock" to "Thunder Shock",
        "thunderwave" to "Thunder Wave",
        "tickle" to "Tickle",
        "tidyup" to "Tidy Up",
        "topsyturvy" to "Topsy-Turvy",
        "torchsong" to "Torch Song",
        "torment" to "Torment",
        "toxic" to "Toxic",
        "toxicspikes" to "Toxic Spikes",
        "toxicthread" to "Toxic Thread",
        "trailblaze" to "Trailblaze",
        "transform" to "Transform",
        "triattack" to "Tri Attack",
        "trick" to "Trick",
        "trickortreat" to "Trick-or-Treat",
        "trickroom" to "Trick Room",
        "triplearrows" to "Triple Arrows",
        "tripleaxel" to "Triple Axel",
        "tripledive" to "Triple Dive",
        "triplekick" to "Triple Kick",
        "tropkick" to "Trop Kick",
        "trumpcard" to "Trump Card",
        "twinbeam" to "Twin Beam",
        "twineedle" to "Twineedle",
        "twinkletackle" to "Twinkle Tackle",
        "twister" to "Twister",
        "upperhand" to "Upper Hand",
        "uproar" to "Uproar",
        "uturn" to "U-turn",
        "vacuumwave" to "Vacuum Wave",
        "vcreate" to "V-create",
        "veeveevolley" to "Veevee Volley",
        "venomdrench" to "Venom Drench",
        "venoshock" to "Venoshock",
        "victorydance" to "Victory Dance",
        "vinewhip" to "Vine Whip",
        "visegrip" to "Vise Grip",
        "vitalthrow" to "Vital Throw",
        "voltswitch" to "Volt Switch",
        "volttackle" to "Volt Tackle",
        "wakeupslap" to "Wake-Up Slap",
        "waterfall" to "Waterfall",
        "watergun" to "Water Gun",
        "waterpledge" to "Water Pledge",
        "waterpulse" to "Water Pulse",
        "watershuriken" to "Water Shuriken",
        "watersport" to "Water Sport",
        "waterspout" to "Water Spout",
        "wavecrash" to "Wave Crash",
        "weatherball" to "Weather Ball",
        "whirlpool" to "Whirlpool",
        "whirlwind" to "Whirlwind",
        "wickedblow" to "Wicked Blow",
        "wickedtorque" to "Wicked Torque",
        "wideguard" to "Wide Guard",
        "wildboltstorm" to "Wildbolt Storm",
        "wildcharge" to "Wild Charge",
        "willowisp" to "Will-O-Wisp",
        "wingattack" to "Wing Attack",
        "wish" to "Wish",
        "withdraw" to "Withdraw",
        "wonderroom" to "Wonder Room",
        "woodhammer" to "Wood Hammer",
        "workup" to "Work Up",
        "worryseed" to "Worry Seed",
        "wrap" to "Wrap",
        "wringout" to "Wring Out",
        "xscissor" to "X-Scissor",
        "yawn" to "Yawn",
        "zapcannon" to "Zap Cannon",
        "zenheadbutt" to "Zen Headbutt",
        "zingzap" to "Zing Zap",
        "zippyzap" to "Zippy Zap"
    )

    // =============================================================================================
    //  Complete ability name lookup map sourced from Pokemon Showdown official data.
    //  Maps concatenated-lowercase IDs to their proper display names.
    // =============================================================================================
    private val ABILITY_NAMES = mapOf(
        "adaptability" to "Adaptability",
        "aerilate" to "Aerilate",
        "aftermath" to "Aftermath",
        "airlock" to "Air Lock",
        "analytic" to "Analytic",
        "angerpoint" to "Anger Point",
        "angershell" to "Anger Shell",
        "anticipation" to "Anticipation",
        "arenatrap" to "Arena Trap",
        "armortail" to "Armor Tail",
        "aromaveil" to "Aroma Veil",
        "asoneglastrier" to "As One (Glastrier)",
        "asonespectrier" to "As One (Spectrier)",
        "aurabreak" to "Aura Break",
        "baddreams" to "Bad Dreams",
        "ballfetch" to "Ball Fetch",
        "battery" to "Battery",
        "battlearmor" to "Battle Armor",
        "battlebond" to "Battle Bond",
        "beadsofruin" to "Beads of Ruin",
        "beastboost" to "Beast Boost",
        "berserk" to "Berserk",
        "bigpecks" to "Big Pecks",
        "blaze" to "Blaze",
        "bulletproof" to "Bulletproof",
        "cheekpouch" to "Cheek Pouch",
        "chillingneigh" to "Chilling Neigh",
        "chlorophyll" to "Chlorophyll",
        "clearbody" to "Clear Body",
        "cloudnine" to "Cloud Nine",
        "colorchange" to "Color Change",
        "comatose" to "Comatose",
        "commander" to "Commander",
        "competitive" to "Competitive",
        "compoundeyes" to "Compound Eyes",
        "contrary" to "Contrary",
        "corrosion" to "Corrosion",
        "costar" to "Costar",
        "cottondown" to "Cotton Down",
        "cudchew" to "Cud Chew",
        "curiousmedicine" to "Curious Medicine",
        "cursedbody" to "Cursed Body",
        "cutecharm" to "Cute Charm",
        "damp" to "Damp",
        "dancer" to "Dancer",
        "darkaura" to "Dark Aura",
        "dauntlessshield" to "Dauntless Shield",
        "dazzling" to "Dazzling",
        "defeatist" to "Defeatist",
        "defiant" to "Defiant",
        "deltastream" to "Delta Stream",
        "desolateland" to "Desolate Land",
        "disguise" to "Disguise",
        "download" to "Download",
        "dragonize" to "Dragonize",
        "dragonsmaw" to "Dragon's Maw",
        "drizzle" to "Drizzle",
        "drought" to "Drought",
        "dryskin" to "Dry Skin",
        "earlybird" to "Early Bird",
        "eartheater" to "Earth Eater",
        "effectspore" to "Effect Spore",
        "electricsurge" to "Electric Surge",
        "electromorphosis" to "Electromorphosis",
        "embodyaspectcornerstone" to "Embody Aspect (Cornerstone)",
        "embodyaspecthearthflame" to "Embody Aspect (Hearthflame)",
        "embodyaspectteal" to "Embody Aspect (Teal)",
        "embodyaspectwellspring" to "Embody Aspect (Wellspring)",
        "emergencyexit" to "Emergency Exit",
        "fairyaura" to "Fairy Aura",
        "filter" to "Filter",
        "flamebody" to "Flame Body",
        "flareboost" to "Flare Boost",
        "flashfire" to "Flash Fire",
        "flowergift" to "Flower Gift",
        "flowerveil" to "Flower Veil",
        "fluffy" to "Fluffy",
        "forecast" to "Forecast",
        "forewarn" to "Forewarn",
        "friendguard" to "Friend Guard",
        "frisk" to "Frisk",
        "fullmetalbody" to "Full Metal Body",
        "furcoat" to "Fur Coat",
        "galewings" to "Gale Wings",
        "galvanize" to "Galvanize",
        "gluttony" to "Gluttony",
        "goodasgold" to "Good as Gold",
        "gooey" to "Gooey",
        "grasspelt" to "Grass Pelt",
        "grassysurge" to "Grassy Surge",
        "grimneigh" to "Grim Neigh",
        "guarddog" to "Guard Dog",
        "gulpmissile" to "Gulp Missile",
        "guts" to "Guts",
        "hadronengine" to "Hadron Engine",
        "harvest" to "Harvest",
        "healer" to "Healer",
        "heatproof" to "Heatproof",
        "heavymetal" to "Heavy Metal",
        "honeygather" to "Honey Gather",
        "hospitality" to "Hospitality",
        "hugepower" to "Huge Power",
        "hungerswitch" to "Hunger Switch",
        "hustle" to "Hustle",
        "hydration" to "Hydration",
        "hypercutter" to "Hyper Cutter",
        "icebody" to "Ice Body",
        "iceface" to "Ice Face",
        "icescales" to "Ice Scales",
        "illuminate" to "Illuminate",
        "illusion" to "Illusion",
        "immunity" to "Immunity",
        "imposter" to "Imposter",
        "infiltrator" to "Infiltrator",
        "innardsout" to "Innards Out",
        "innerfocus" to "Inner Focus",
        "insomnia" to "Insomnia",
        "intimidate" to "Intimidate",
        "intrepidsword" to "Intrepid Sword",
        "ironbarbs" to "Iron Barbs",
        "ironfist" to "Iron Fist",
        "justified" to "Justified",
        "keeneye" to "Keen Eye",
        "klutz" to "Klutz",
        "leafguard" to "Leaf Guard",
        "levitate" to "Levitate",
        "libero" to "Libero",
        "lightmetal" to "Light Metal",
        "lightningrod" to "Lightning Rod",
        "limber" to "Limber",
        "lingeringaroma" to "Lingering Aroma",
        "liquidooze" to "Liquid Ooze",
        "liquidvoice" to "Liquid Voice",
        "longreach" to "Long Reach",
        "magicbounce" to "Magic Bounce",
        "magicguard" to "Magic Guard",
        "magician" to "Magician",
        "magmaarmor" to "Magma Armor",
        "magnetpull" to "Magnet Pull",
        "marvelscale" to "Marvel Scale",
        "megalauncher" to "Mega Launcher",
        "megasol" to "Mega Sol",
        "merciless" to "Merciless",
        "mimicry" to "Mimicry",
        "mindseye" to "Mind's Eye",
        "minus" to "Minus",
        "mirrorarmor" to "Mirror Armor",
        "mistysurge" to "Misty Surge",
        "moldbreaker" to "Mold Breaker",
        "moody" to "Moody",
        "motordrive" to "Motor Drive",
        "mountaineer" to "Mountaineer",
        "moxie" to "Moxie",
        "multiscale" to "Multiscale",
        "multitype" to "Multitype",
        "mummy" to "Mummy",
        "myceliummight" to "Mycelium Might",
        "naturalcure" to "Natural Cure",
        "neuroforce" to "Neuroforce",
        "neutralizinggas" to "Neutralizing Gas",
        "noability" to "No Ability",
        "noguard" to "No Guard",
        "normalize" to "Normalize",
        "oblivious" to "Oblivious",
        "opportunist" to "Opportunist",
        "orichalcumpulse" to "Orichalcum Pulse",
        "overcoat" to "Overcoat",
        "overgrow" to "Overgrow",
        "owntempo" to "Own Tempo",
        "parentalbond" to "Parental Bond",
        "pastelveil" to "Pastel Veil",
        "perishbody" to "Perish Body",
        "persistent" to "Persistent",
        "pickpocket" to "Pickpocket",
        "pickup" to "Pickup",
        "piercingdrill" to "Piercing Drill",
        "pixilate" to "Pixilate",
        "plus" to "Plus",
        "poisonheal" to "Poison Heal",
        "poisonpoint" to "Poison Point",
        "poisonpuppeteer" to "Poison Puppeteer",
        "poisontouch" to "Poison Touch",
        "powerconstruct" to "Power Construct",
        "powerofalchemy" to "Power of Alchemy",
        "powerspot" to "Power Spot",
        "prankster" to "Prankster",
        "pressure" to "Pressure",
        "primordialsea" to "Primordial Sea",
        "prismarmor" to "Prism Armor",
        "propellertail" to "Propeller Tail",
        "protean" to "Protean",
        "protosynthesis" to "Protosynthesis",
        "psychicsurge" to "Psychic Surge",
        "punkrock" to "Punk Rock",
        "purepower" to "Pure Power",
        "purifyingsalt" to "Purifying Salt",
        "quarkdrive" to "Quark Drive",
        "queenlymajesty" to "Queenly Majesty",
        "quickdraw" to "Quick Draw",
        "quickfeet" to "Quick Feet",
        "raindish" to "Rain Dish",
        "rattled" to "Rattled",
        "rebound" to "Rebound",
        "receiver" to "Receiver",
        "reckless" to "Reckless",
        "refrigerate" to "Refrigerate",
        "regenerator" to "Regenerator",
        "ripen" to "Ripen",
        "rivalry" to "Rivalry",
        "rkssystem" to "RKS System",
        "rockhead" to "Rock Head",
        "rockypayload" to "Rocky Payload",
        "roughskin" to "Rough Skin",
        "runaway" to "Run Away",
        "sandforce" to "Sand Force",
        "sandrush" to "Sand Rush",
        "sandspit" to "Sand Spit",
        "sandstream" to "Sand Stream",
        "sandveil" to "Sand Veil",
        "sapsipper" to "Sap Sipper",
        "schooling" to "Schooling",
        "scrappy" to "Scrappy",
        "screencleaner" to "Screen Cleaner",
        "seedsower" to "Seed Sower",
        "serenegrace" to "Serene Grace",
        "shadowshield" to "Shadow Shield",
        "shadowtag" to "Shadow Tag",
        "sharpness" to "Sharpness",
        "shedskin" to "Shed Skin",
        "sheerforce" to "Sheer Force",
        "shellarmor" to "Shell Armor",
        "shielddust" to "Shield Dust",
        "shieldsdown" to "Shields Down",
        "simple" to "Simple",
        "skilllink" to "Skill Link",
        "slowstart" to "Slow Start",
        "slushrush" to "Slush Rush",
        "sniper" to "Sniper",
        "snowcloak" to "Snow Cloak",
        "snowwarning" to "Snow Warning",
        "solarpower" to "Solar Power",
        "solidrock" to "Solid Rock",
        "soulheart" to "Soul-Heart",
        "soundproof" to "Soundproof",
        "speedboost" to "Speed Boost",
        "spicyspray" to "Spicy Spray",
        "stakeout" to "Stakeout",
        "stall" to "Stall",
        "stalwart" to "Stalwart",
        "stamina" to "Stamina",
        "stancechange" to "Stance Change",
        "static" to "Static",
        "steadfast" to "Steadfast",
        "steamengine" to "Steam Engine",
        "steelworker" to "Steelworker",
        "steelyspirit" to "Steely Spirit",
        "stench" to "Stench",
        "stickyhold" to "Sticky Hold",
        "stormdrain" to "Storm Drain",
        "strongjaw" to "Strong Jaw",
        "sturdy" to "Sturdy",
        "suctioncups" to "Suction Cups",
        "superluck" to "Super Luck",
        "supersweetsyrup" to "Supersweet Syrup",
        "supremeoverlord" to "Supreme Overlord",
        "surgesurfer" to "Surge Surfer",
        "swarm" to "Swarm",
        "sweetveil" to "Sweet Veil",
        "swiftswim" to "Swift Swim",
        "swordofruin" to "Sword of Ruin",
        "symbiosis" to "Symbiosis",
        "synchronize" to "Synchronize",
        "tabletsofruin" to "Tablets of Ruin",
        "tangledfeet" to "Tangled Feet",
        "tanglinghair" to "Tangling Hair",
        "technician" to "Technician",
        "telepathy" to "Telepathy",
        "teraformzero" to "Teraform Zero",
        "terashell" to "Tera Shell",
        "terashift" to "Tera Shift",
        "teravolt" to "Teravolt",
        "thermalexchange" to "Thermal Exchange",
        "thickfat" to "Thick Fat",
        "tintedlens" to "Tinted Lens",
        "torrent" to "Torrent",
        "toughclaws" to "Tough Claws",
        "toxicboost" to "Toxic Boost",
        "toxicchain" to "Toxic Chain",
        "toxicdebris" to "Toxic Debris",
        "trace" to "Trace",
        "transistor" to "Transistor",
        "triage" to "Triage",
        "truant" to "Truant",
        "turboblaze" to "Turboblaze",
        "unaware" to "Unaware",
        "unburden" to "Unburden",
        "unnerve" to "Unnerve",
        "unseenfist" to "Unseen Fist",
        "vesselofruin" to "Vessel of Ruin",
        "victorystar" to "Victory Star",
        "vitalspirit" to "Vital Spirit",
        "voltabsorb" to "Volt Absorb",
        "wanderingspirit" to "Wandering Spirit",
        "waterabsorb" to "Water Absorb",
        "waterbubble" to "Water Bubble",
        "watercompaction" to "Water Compaction",
        "waterveil" to "Water Veil",
        "weakarmor" to "Weak Armor",
        "wellbakedbody" to "Well-Baked Body",
        "whitesmoke" to "White Smoke",
        "wimpout" to "Wimp Out",
        "windpower" to "Wind Power",
        "windrider" to "Wind Rider",
        "wonderguard" to "Wonder Guard",
        "wonderskin" to "Wonder Skin",
        "zenmode" to "Zen Mode",
        "zerotohero" to "Zero to Hero"
    )
}
